BACKTEST_START = "2025-06-01"
BACKTEST_END = "2026-06-01"
NUM_TOKENS = 100

CANDLE_INTERVAL_HOURS = 4
SENTIMENT_DECAY_THRESHOLD = 0.25
PRICE_MOMENTUM_MAX = 0.10
PRICE_FLAT_MIN = -0.05
PRICE_FLAT_MAX = 0.05
FEAR_GREED_THRESHOLD = 65
EXIT_HOLD_CANDLES = 60
EXIT_PROFIT_TARGET = 0.20
EXIT_FEAR_GREED_FLOOR = 40
STARTING_CAPITAL = 10000
POSITION_SIZE_FRACTION = 0.10
VOLUME_DECLINING_THRESHOLD = 0.0
SENTIMENT_LOOKBACK = 6
MAX_SIMULTANEOUS_POSITIONS = 15

SEED = 42

TOKEN_NAMES = [
    "PEPE", "FLOKI", "DOGE", "MOG", "POPCAT", "BONK", "MEME", "SHIB",
    "WIF", "DOGS", "NEIRO", "BRETT", "COQ", "MYRO", "SAMO", "KISHU",
    "AKITA", "HOSKY", "ELON", "BABYDOGE", "MONKEY", "PENG", "CHAD",
    "WOJAK", "SPONGE", "TURBO", "HARRY", "AIDOGE", "BOBO", "PORK",
    "RATS", "GROK", "CHINU", "PEPE2", "MOON", "BOME", "SLERF", "TOSHI",
    "CORGIAI", "KEKIUS", "ANDY", "BOB", "APU", "COCO", "LADYS", "MEW",
    "SIGMA", "GIGA", "DOGE20", "PEPECOIN",
    "SOLAMA", "BONKI", "FROG", "DUCK", "MOCHI", "SUSHI", "RAMEN",
    "PIZZA", "BURGER", "TACO", "DONUT", "WAFFLE", "PANCAKE", "BAGEL",
    "DANGO", "MOONI", "STARL", "NOVA", "COMET", "ASTRO",
    "GALAXY", "NEBULA", "QUASAR", "PULSAR", "METEOR", "ORBIT", "SATURN",
    "JUPITER", "MARS", "VENUS", "PLUTO", "NEPTUNE", "MERCURY", "URANUS",
    "ECLIPSE", "SOLSTICE", "EQUINOX", "AURORA", "ZENITH", "HORIZON",
    "INFINITE", "ETERNAL", "PHANTOM", "SPECTRE", "GHOST", "SHADOW",
    "DREAM", "NIGHTMARE", "VISION", "MIRAGE", "OSPREY"
]

FEAR_GREED_REGIME_MEANS = {"fear": 25, "normal": 50, "greed": 75}
FEAR_GREED_REGIME_STD = {"fear": 8, "normal": 10, "greed": 8}
FEAR_GREED_MIN = 5
FEAR_GREED_MAX = 95
REGIME_TRANSITION_PROB = 0.02

INITIAL_PRICE_RANGE = (0.0001, 10.0)
BASE_DRIFT = 0.0001
BASE_VOLATILITY = 0.025
PUMP_PROBABILITY = 0.004
PUMP_MAGNITUDE_RANGE = (0.20, 0.60)
PUMP_DURATION_RANGE = (1, 4)
CRASH_MAGNITUDE_RANGE = (0.25, 0.55)
VOLUME_BASE = 1000000
VOLUME_VOLATILITY = 0.3
FG_CORRELATION_STRENGTH = 0.15

COLLAPSE_VOLUME_DECAY = 0.35
BOUNCE_VOLUME_SUSTAIN = 0.7
